//! Generated by bdl-codegen-rust 0.1.0 for design `semantic`. Do not edit.
//!
//! One global tick = `step`: read phase (every due declaration, in plan order,
//! reading inputs, declarations evaluated earlier this tick, and *committed* state),
//! write phase (every cell whose writing domain is active, into the next state),
//! commit, then output projection.  Nothing is mutated in place; reads never see
//! writes of the same tick.  Semantics: docs/spec/runtime-semantics.md.

#![no_std]
#![forbid(unsafe_code)]
#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, clippy::all)]

use bdl_runtime_core::num;
use bdl_runtime_core::prim;
use bdl_runtime_core::read_decl;
use bdl_runtime_core::read_input;
use bdl_runtime_core::ActiveDomains;
use bdl_runtime_core::ClockSlot;
use bdl_runtime_core::RuntimeError;

/// The design this core was generated from.
pub const DESIGN: &str = "semantic";

/// Whether the design has any clock domain; decides when domain-agnostic declarations run (DI-16).
pub const HAS_DOMAINS: bool = true;

pub const CLOCK_COUNT: u16 = 1_u16;

/// Clock domain `clk#0` (clk#0).
pub const CLOCK_0: ClockSlot = ClockSlot(0_u16);

/// Concept `Tilt` (sem#0): q[rad].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sem0(pub f64);

/// Concept `Held` (sem#1): bool.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sem1(pub bool);

/// Temporal state: one slot per `delay`/`sync` site, `None` until first written.
/// Slot ↔ `StateCellId` in `bdl-manifest.json`.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Cells {}

/// Everything that survives from one tick to the next.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct State {
    pub cells: Cells,
}

/// Values for the unresolved declarations at one tick.
/// A `None` for a declaration that is due is `RuntimeError::MissingInput`, never a default.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Inputs {
    pub decl_0: Option<Sem0>,
    pub decl_2: Option<Sem1>,
}

/// Every declaration's value at one tick; `None` when it was not due.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Values {
    pub decl_0: Option<Sem0>,
    pub decl_1: Option<Sem1>,
    pub decl_2: Option<Sem1>,
    pub decl_3: Option<bool>,
}

/// Physical outputs committed at one tick: the single driver's value, `None` when the driver was not due.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Outputs {}

/// The observable result of one tick.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Tick {
    pub values: Values,
    pub outputs: Outputs,
}

/// The initial state: no cell has been written.
pub fn init() -> State {
    State::default()
}

/// One global tick with the given active domains and inputs.
/// On `Err` the state is unchanged.
pub fn step(state: &mut State, active: ActiveDomains, inputs: &Inputs) -> Result<Tick, RuntimeError> {
    let prev: &Cells = &state.cells;
    let mut next: Cells = state.cells.clone();
    // read phase
    // tilt (decl#0)
    let decl_0: Option<Sem0> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_0, 0_u64)?) } else { None };
    // steep (decl#1)
    let decl_1: Option<Sem1> = if active.is_active(CLOCK_0) { Some(Sem1((0.5_f64 < read_decl(&decl_0, 0_u64)?.0))) } else { None };
    // held (decl#2)
    let decl_2: Option<Sem1> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_2, 2_u64)?) } else { None };
    // both (decl#3)
    let decl_3: Option<bool> = if active.is_active(CLOCK_0) { Some(prim::and(read_decl(&decl_1, 1_u64)?.0, read_decl(&decl_2, 2_u64)?.0)) } else { None };
    // write phase: into the next state only
    // commit
    state.cells = next;
    Ok(Tick { values: Values { decl_0: decl_0, decl_1: decl_1, decl_2: decl_2, decl_3: decl_3 }, outputs: Outputs {} })
}
