//! Generated by bdl-codegen-rust 0.1.0 for design `arith`. Do not edit.
//!
//! One global tick = `step`: read phase (every due declaration, in plan order,
//! reading inputs, declarations evaluated earlier this tick, and *committed* state),
//! write phase (every cell whose writing domain is active, into the next state),
//! commit, then output projection.  Nothing is mutated in place; reads never see
//! writes of the same tick.  Semantics: docs/spec/runtime-semantics.md.

#![no_std]
#![forbid(unsafe_code)]
#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, clippy::all)]

use bdl_runtime_core::num;
use bdl_runtime_core::prim;
use bdl_runtime_core::read_decl;
use bdl_runtime_core::read_input;
use bdl_runtime_core::ActiveDomains;
use bdl_runtime_core::ClockSlot;
use bdl_runtime_core::RuntimeError;

/// The design this core was generated from.
pub const DESIGN: &str = "arith";

/// Whether the design has any clock domain; decides when domain-agnostic declarations run (DI-16).
pub const HAS_DOMAINS: bool = true;

pub const CLOCK_COUNT: u16 = 1_u16;

/// Clock domain `main` (clk#0).
pub const CLOCK_0: ClockSlot = ClockSlot(0_u16);

/// Temporal state: one slot per `delay`/`sync` site, `None` until first written.
/// Slot ↔ `StateCellId` in `bdl-manifest.json`.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Cells {}

/// Everything that survives from one tick to the next.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct State {
    pub cells: Cells,
}

/// Values for the unresolved declarations at one tick.
/// A `None` for a declaration that is due is `RuntimeError::MissingInput`, never a default.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Inputs {}

/// Every declaration's value at one tick; `None` when it was not due.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Values {
    pub decl_0: Option<f64>,
    pub decl_1: Option<f64>,
    pub decl_2: Option<f64>,
    pub decl_3: Option<u64>,
}

/// Physical outputs committed at one tick: the single driver's value, `None` when the driver was not due.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Outputs {}

/// The observable result of one tick.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Tick {
    pub values: Values,
    pub outputs: Outputs,
}

/// The initial state: no cell has been written.
pub fn init() -> State {
    State::default()
}

/// One global tick with the given active domains and inputs.
/// On `Err` the state is unchanged.
pub fn step(state: &mut State, active: ActiveDomains, inputs: &Inputs) -> Result<Tick, RuntimeError> {
    let prev: &Cells = &state.cells;
    let mut next: Cells = state.cells.clone();
    // read phase
    // area (decl#0)
    let decl_0: Option<f64> = if active.is_active(CLOCK_0) { Some(num::mul(2.5_f64, 4.0_f64, 0_u64)?) } else { None };
    // speed (decl#1)
    let decl_1: Option<f64> = if active.is_active(CLOCK_0) { Some(num::div(100.0_f64, 9.58_f64, 1_u64)?) } else { None };
    // poly (decl#2)
    let decl_2: Option<f64> = if active.is_active(CLOCK_0) { Some(num::sub(num::add(num::mul(2.0_f64, 3.0_f64, 2_u64)?, 0.1_f64, 2_u64)?, num::div(1.0_f64, 3.0_f64, 2_u64)?, 2_u64)?) } else { None };
    // count (decl#3)
    let decl_3: Option<u64> = if active.is_active(CLOCK_0) { Some(7_u64) } else { None };
    // write phase: into the next state only
    // commit
    state.cells = next;
    Ok(Tick { values: Values { decl_0: decl_0, decl_1: decl_1, decl_2: decl_2, decl_3: decl_3 }, outputs: Outputs {} })
}
