[workspace]
resolver = "2"
members = [
    "crates/bdl-model",
    "crates/bdl-ir",
    "crates/bdl-diagnostics",
    "crates/bdl-syntax",
    "crates/bdl-elab",
    "crates/bdl-check",
    "crates/bdl-reactive",
    "crates/bdl-output",
    "crates/bdl-hardware",
    "crates/bdl-exec-ir",
    "crates/bdl-lower",
    "crates/bdl-codegen-rust",
    "crates/bdl-compiler",
    "crates/bdl-system",
    "crates/bdl-protocol",
    "crates/bdl-daemon",
    "runtime/bdl-runtime-core",
    "runtime/bdl-runtime-host",
    "crates/bdl-library",
    "crates/bdl-ide-db",
    "crates/bdl-ide",
    "crates/bdl-lsp",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KCN-judu/BDL"

[workspace.dependencies]
bdl-model = { path = "crates/bdl-model" }
bdl-ir = { path = "crates/bdl-ir" }
bdl-diagnostics = { path = "crates/bdl-diagnostics" }
bdl-syntax = { path = "crates/bdl-syntax" }
bdl-elab = { path = "crates/bdl-elab" }
bdl-check = { path = "crates/bdl-check" }
bdl-reactive = { path = "crates/bdl-reactive" }
bdl-output = { path = "crates/bdl-output" }
bdl-hardware = { path = "crates/bdl-hardware" }
bdl-exec-ir = { path = "crates/bdl-exec-ir" }
bdl-lower = { path = "crates/bdl-lower" }
bdl-codegen-rust = { path = "crates/bdl-codegen-rust" }
bdl-runtime-core = { path = "runtime/bdl-runtime-core" }
bdl-runtime-host = { path = "runtime/bdl-runtime-host" }
bdl-compiler = { path = "crates/bdl-compiler" }
bdl-system = { path = "crates/bdl-system" }
bdl-protocol = { path = "crates/bdl-protocol" }
bdl-library = { path = "crates/bdl-library" }
bdl-ide-db = { path = "crates/bdl-ide-db" }
bdl-ide = { path = "crates/bdl-ide" }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
thiserror = "2.0"
toml = "0.9"
prost = "0.14"
prost-build = "0.14"
protox = "0.9"
bytes = "1"
tokio = { version = "1.53", features = ["rt-multi-thread", "io-std", "io-util", "sync", "macros", "process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
tempfile = "3"
proptest = "1"
logos = "0.16"
rowan = "0.17"
lsp-server = "0.10"
lsp-types = "0.97"
crossbeam-channel = "0.5"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "warn"
