include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - lib/protocol/gen/**

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
