//! Generated by bdl-codegen-rust 0.1.0 for design `list_ops`. Do not edit.
//!
//! One global tick = `step`: read phase (every due declaration, in plan order,
//! reading inputs, declarations evaluated earlier this tick, and *committed* state),
//! write phase (every cell whose writing domain is active, into the next state),
//! commit, then output projection.  Nothing is mutated in place; reads never see
//! writes of the same tick.  Semantics: docs/spec/runtime-semantics.md.

#![no_std]
#![forbid(unsafe_code)]
#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, clippy::all)]

extern crate alloc;
use alloc::vec::Vec;
use bdl_runtime_core::list;
use bdl_runtime_core::num;
use bdl_runtime_core::prim;
use bdl_runtime_core::read_decl;
use bdl_runtime_core::read_decl_ref;
use bdl_runtime_core::read_input;
use bdl_runtime_core::ActiveDomains;
use bdl_runtime_core::ClockSlot;
use bdl_runtime_core::RuntimeError;

/// The design this core was generated from.
pub const DESIGN: &str = "list_ops";

/// Whether the design has any clock domain; decides when domain-agnostic declarations run (DI-16).
pub const HAS_DOMAINS: bool = true;

pub const CLOCK_COUNT: u16 = 1_u16;

/// Clock domain `main` (clk#0).
pub const CLOCK_0: ClockSlot = ClockSlot(0_u16);

/// Temporal state: one slot per `delay`/`sync` site, `None` until first written.
/// Slot ↔ `StateCellId` in `bdl-manifest.json`.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Cells {}

/// Everything that survives from one tick to the next.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct State {
    pub cells: Cells,
}

/// Values for the unresolved declarations at one tick.
/// A `None` for a declaration that is due is `RuntimeError::MissingInput`, never a default.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Inputs {
    pub decl_0: Option<Vec<f64>>,
}

/// Every declaration's value at one tick; `None` when it was not due.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Values {
    pub decl_0: Option<Vec<f64>>,
    pub decl_1: Option<Vec<f64>>,
    pub decl_2: Option<Vec<f64>>,
    pub decl_3: Option<Vec<f64>>,
    pub decl_4: Option<Vec<(f64, f64)>>,
    pub decl_5: Option<f64>,
    pub decl_6: Option<bool>,
    pub decl_7: Option<Vec<f64>>,
}

/// Physical outputs committed at one tick: the single driver's value, `None` when the driver was not due.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Outputs {}

/// The observable result of one tick.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Tick {
    pub values: Values,
    pub outputs: Outputs,
}

/// The initial state: no cell has been written.
pub fn init() -> State {
    State::default()
}

/// One global tick with the given active domains and inputs.
/// On `Err` the state is unchanged.
pub fn step(state: &mut State, active: ActiveDomains, inputs: &Inputs) -> Result<Tick, RuntimeError> {
    let prev: &Cells = &state.cells;
    // read phase
    // xs (decl#0)
    let decl_0: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_0, 0_u64)?) } else { None };
    // mapped (decl#1)
    let decl_1: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some({ let l0 = read_decl(&decl_0, 0_u64)?; list::fold(l0, list::nil::<f64>(), |l1, l2| Ok({ let l3 = l1; { let l4 = l2; list::cons({ let l5 = l3; num::add(l5, 1.0_f64, 1_u64)? }, l4) } }))? }) } else { None };
    // kept (decl#2)
    let decl_2: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some({ let l6 = read_decl(&decl_0, 0_u64)?; list::fold(l6, list::nil::<f64>(), |l7, l8| Ok({ let l9 = l7; { let l10 = l8; if { let l11 = l9.clone(); (&l11 < &100.0_f64) } { list::cons(l9.clone(), l10) } else { l10 } } }))? }) } else { None };
    // joined (decl#3)
    let decl_3: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some({ let l12 = read_decl(&decl_2, 2_u64)?; { let l13 = read_decl(&decl_1, 1_u64)?; list::fold(l12, l13, |l14, l15| Ok(list::cons(l14, l15)))? } }) } else { None };
    // pairs (decl#4)
    let decl_4: Option<Vec<(f64, f64)>> = if active.is_active(CLOCK_0) { Some({ let l16 = read_decl(&decl_0, 0_u64)?; { let l17 = read_decl(&decl_1, 1_u64)?; list::reverse(list::fold(list::reverse(l16), (l17, list::nil::<(f64, f64)>()), |l18, l19| Ok({ let l20 = l18; { let l21 = l19; (list::drop(1.0_f64, l21.clone().0), list::fold(list::fold(list::take_of(1.0_f64, &l21.clone().0), list::nil::<(f64, f64)>(), |l22, l23| Ok({ let l24 = l22; { let l25 = l23; list::cons((l20.clone(), l24), l25) } }))?, l21.clone().1, |l26, l27| Ok(list::cons(l26, l27)))?) } }))?.1) } }) } else { None };
    // total (decl#5)
    let decl_5: Option<f64> = if active.is_active(CLOCK_0) { Some({ let l28 = read_decl(&decl_3, 3_u64)?; list::fold(l28, 0.0_f64, |l29, l30| Ok(num::add(l29, l30, 5_u64)?))? }) } else { None };
    // seen150 (decl#6)
    let decl_6: Option<bool> = if active.is_active(CLOCK_0) { Some({ let l31 = 150.0_f64; { let l32 = read_decl(&decl_0, 0_u64)?; list::fold(l32, false, |l33, l34| Ok({ let l35 = l33; { let l36 = l34; prim::or((&l31 == &l35), l36) } }))? } }) } else { None };
    // firstTwo (decl#7)
    let decl_7: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some(list::take_of(2.0_f64, &list::reverse(read_decl(&decl_3, 3_u64)?))) } else { None };
    // write phase: every active writer's operand, before any commit
    // commit: only the cells written this tick change; nothing else is copied
    Ok(Tick { values: Values { decl_0: decl_0, decl_1: decl_1, decl_2: decl_2, decl_3: decl_3, decl_4: decl_4, decl_5: decl_5, decl_6: decl_6, decl_7: decl_7 }, outputs: Outputs {} })
}
