//! Generated by bdl-codegen-rust 0.1.0 for design `nested`. Do not edit.
//!
//! One global tick = `step`: read phase (every due declaration, in plan order,
//! reading inputs, declarations evaluated earlier this tick, and *committed* state),
//! write phase (every cell whose writing domain is active, into the next state),
//! commit, then output projection.  Nothing is mutated in place; reads never see
//! writes of the same tick.  Semantics: docs/spec/runtime-semantics.md.

#![no_std]
#![forbid(unsafe_code)]
#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, clippy::all)]

extern crate alloc;
use alloc::vec::Vec;
use bdl_runtime_core::list;
use bdl_runtime_core::num;
use bdl_runtime_core::prim;
use bdl_runtime_core::read_decl;
use bdl_runtime_core::read_decl_ref;
use bdl_runtime_core::read_input;
use bdl_runtime_core::ActiveDomains;
use bdl_runtime_core::ClockSlot;
use bdl_runtime_core::RuntimeError;

/// The design this core was generated from.
pub const DESIGN: &str = "nested";

/// Whether the design has any clock domain; decides when domain-agnostic declarations run (DI-16).
pub const HAS_DOMAINS: bool = true;

pub const CLOCK_COUNT: u16 = 1_u16;

/// Clock domain `main` (clk#0).
pub const CLOCK_0: ClockSlot = ClockSlot(0_u16);

/// Temporal state: one slot per `delay`/`sync` site, `None` until first written.
/// Slot ↔ `StateCellId` in `bdl-manifest.json`.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Cells {}

/// Everything that survives from one tick to the next.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct State {
    pub cells: Cells,
}

/// Values for the unresolved declarations at one tick.
/// A `None` for a declaration that is due is `RuntimeError::MissingInput`, never a default.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Inputs {
    pub decl_0: Option<Vec<(f64, f64)>>,
}

/// Every declaration's value at one tick; `None` when it was not due.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Values {
    pub decl_0: Option<Vec<(f64, f64)>>,
    pub decl_1: Option<Vec<f64>>,
    pub decl_2: Option<(Vec<f64>, f64)>,
    pub decl_3: Option<Vec<Vec<f64>>>,
    pub decl_4: Option<Vec<f64>>,
    pub decl_5: Option<bool>,
}

/// Physical outputs committed at one tick: the single driver's value, `None` when the driver was not due.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Outputs {}

/// Raw commands of the realised outputs at one tick: each device binding's encoder applied to its output's value, `None` when the driver was not due.
/// Downstream of `Values` and `Outputs`, which never depend on it (docs/architecture/output-realization.md).
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Commands {}

/// The observable result of one tick.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Tick {
    pub values: Values,
    pub outputs: Outputs,
    pub commands: Commands,
}

/// The initial state: no cell has been written.
pub fn init() -> State {
    State::default()
}

/// One global tick with the given active domains and inputs.
/// On `Err` the state is unchanged.
pub fn step(state: &mut State, active: ActiveDomains, inputs: &Inputs) -> Result<Tick, RuntimeError> {
    let prev: &Cells = &state.cells;
    // read phase
    // ps (decl#0)
    let decl_0: Option<Vec<(f64, f64)>> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_0, 0_u64)?) } else { None };
    // sums (decl#1)
    let decl_1: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some({ let l0 = read_decl(&decl_0, 0_u64)?; list::fold(l0, list::nil::<f64>(), |l1, l2| Ok({ let l3 = l1; { let l4 = l2; list::cons({ let l5 = l3; num::add(l5.clone().0, l5.clone().1, 1_u64)? }, l4) } }))? }) } else { None };
    // grouped (decl#2)
    let decl_2: Option<(Vec<f64>, f64)> = if active.is_active(CLOCK_0) { Some((read_decl(&decl_1, 1_u64)?, list::length_of(read_decl_ref(&decl_0, 0_u64)?))) } else { None };
    // rows (decl#3)
    let decl_3: Option<Vec<Vec<f64>>> = if active.is_active(CLOCK_0) { Some(list::cons(read_decl(&decl_1, 1_u64)?, list::cons(list::reverse(read_decl(&decl_1, 1_u64)?), list::nil::<Vec<f64>>()))) } else { None };
    // firstRow (decl#4)
    let decl_4: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some(prim::get_d(list::head_of(read_decl_ref(&decl_3, 3_u64)?), list::nil::<f64>())) } else { None };
    // sameRows (decl#5)
    let decl_5: Option<bool> = if active.is_active(CLOCK_0) { Some((read_decl_ref(&decl_3, 3_u64)? == read_decl_ref(&decl_3, 3_u64)?)) } else { None };
    // write phase: every active writer's operand, before any commit
    // commit: only the cells written this tick change; nothing else is copied
    // machine sinks: each realised output's raw command, when its driver was due
    Ok(Tick { values: Values { decl_0: decl_0, decl_1: decl_1, decl_2: decl_2, decl_3: decl_3, decl_4: decl_4, decl_5: decl_5 }, outputs: Outputs {}, commands: Commands {} })
}
