// GENERATED by scripts/gen_library_l10n.py from library/std/concepts.toml
// and locale/library/std.json — do not edit by hand.

/// The localized presentation of a Standard Library item, by id:
/// its name, description and search tags in the current locale
/// (docs/project/localization-style.md).  Falls back to the item's
/// canonical English (what the daemon sends) for an id the catalog
/// does not know — a future team or project library.
library;

import 'app_localizations.dart';

class LibraryItemStrings {
  const LibraryItemStrings({required this.name, required this.description, required this.tags});
  final String name;
  final String description;

  /// Space-separated words a search should match, in the locale.
  final String tags;
}

LibraryItemStrings? libraryItemStrings(AppLocalizations l10n, String id) => switch (id) {
  'std.value.boolean' => LibraryItemStrings(
    name: l10n.libItem_std_value_boolean_name,
    description: l10n.libItem_std_value_boolean_description,
    tags: l10n.libItem_std_value_boolean_tags,
  ),
  'std.value.count' => LibraryItemStrings(
    name: l10n.libItem_std_value_count_name,
    description: l10n.libItem_std_value_count_description,
    tags: l10n.libItem_std_value_count_tags,
  ),
  'std.value.level' => LibraryItemStrings(
    name: l10n.libItem_std_value_level_name,
    description: l10n.libItem_std_value_level_description,
    tags: l10n.libItem_std_value_level_tags,
  ),
  'std.value.open' => LibraryItemStrings(
    name: l10n.libItem_std_value_open_name,
    description: l10n.libItem_std_value_open_description,
    tags: l10n.libItem_std_value_open_tags,
  ),
  'std.quantity.angle' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_angle_name,
    description: l10n.libItem_std_quantity_angle_description,
    tags: l10n.libItem_std_quantity_angle_tags,
  ),
  'std.quantity.length' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_length_name,
    description: l10n.libItem_std_quantity_length_description,
    tags: l10n.libItem_std_quantity_length_tags,
  ),
  'std.quantity.time' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_time_name,
    description: l10n.libItem_std_quantity_time_description,
    tags: l10n.libItem_std_quantity_time_tags,
  ),
  'std.quantity.mass' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_mass_name,
    description: l10n.libItem_std_quantity_mass_description,
    tags: l10n.libItem_std_quantity_mass_tags,
  ),
  'std.quantity.current' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_current_name,
    description: l10n.libItem_std_quantity_current_description,
    tags: l10n.libItem_std_quantity_current_tags,
  ),
  'std.quantity.temperature' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_temperature_name,
    description: l10n.libItem_std_quantity_temperature_description,
    tags: l10n.libItem_std_quantity_temperature_tags,
  ),
  'std.quantity.amount' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_amount_name,
    description: l10n.libItem_std_quantity_amount_description,
    tags: l10n.libItem_std_quantity_amount_tags,
  ),
  'std.quantity.luminous_intensity' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_luminous_intensity_name,
    description: l10n.libItem_std_quantity_luminous_intensity_description,
    tags: l10n.libItem_std_quantity_luminous_intensity_tags,
  ),
  'std.quantity.speed' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_speed_name,
    description: l10n.libItem_std_quantity_speed_description,
    tags: l10n.libItem_std_quantity_speed_tags,
  ),
  'std.quantity.acceleration' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_acceleration_name,
    description: l10n.libItem_std_quantity_acceleration_description,
    tags: l10n.libItem_std_quantity_acceleration_tags,
  ),
  'std.quantity.angular_velocity' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_angular_velocity_name,
    description: l10n.libItem_std_quantity_angular_velocity_description,
    tags: l10n.libItem_std_quantity_angular_velocity_tags,
  ),
  'std.quantity.frequency' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_frequency_name,
    description: l10n.libItem_std_quantity_frequency_description,
    tags: l10n.libItem_std_quantity_frequency_tags,
  ),
  'std.quantity.force' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_force_name,
    description: l10n.libItem_std_quantity_force_description,
    tags: l10n.libItem_std_quantity_force_tags,
  ),
  'std.quantity.pressure' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_pressure_name,
    description: l10n.libItem_std_quantity_pressure_description,
    tags: l10n.libItem_std_quantity_pressure_tags,
  ),
  'std.quantity.torque' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_torque_name,
    description: l10n.libItem_std_quantity_torque_description,
    tags: l10n.libItem_std_quantity_torque_tags,
  ),
  'std.quantity.power' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_power_name,
    description: l10n.libItem_std_quantity_power_description,
    tags: l10n.libItem_std_quantity_power_tags,
  ),
  'std.quantity.voltage' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_voltage_name,
    description: l10n.libItem_std_quantity_voltage_description,
    tags: l10n.libItem_std_quantity_voltage_tags,
  ),
  'std.quantity.illuminance' => LibraryItemStrings(
    name: l10n.libItem_std_quantity_illuminance_name,
    description: l10n.libItem_std_quantity_illuminance_description,
    tags: l10n.libItem_std_quantity_illuminance_tags,
  ),
  _ => null,
};
