#!/usr/bin/env python3
"""The Standard Library's localized presentation, into Studio.

Reads the canonical English of every item from ``library/std/concepts.toml``
and the zh-Hans / ja names, descriptions and search tags from
``locale/library/std.json``, and writes:

* ``libItem_<id>_name`` / ``_description`` / ``_tags`` keys into the three
  Studio ARB catalogs (``apps/studio/lib/l10n/app_{en,zh,ja}.arb``) — the
  same pipeline as every other Studio string (``flutter gen-l10n``,
  ``scripts/check_l10n.py``);
* ``apps/studio/lib/l10n/library_strings.dart``: the lookup from an item id
  to those keys, so the Library panel localizes by id and never carries a
  translated string in a protocol or a project.

English tags are the item's ``keywords``.  Identifiers (default names) are
never localized.  Idempotent; ``--check`` exits non-zero when the files
would change.

Usage: ``python3 scripts/gen_library_l10n.py [--check]``.
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOML = ROOT / "library/std/concepts.toml"
L10N = ROOT / "locale/library/std.json"
ARB_DIR = ROOT / "apps/studio/lib/l10n"
ARBS = {"en": "app_en.arb", "zh-Hans": "app_zh.arb", "ja": "app_ja.arb"}
DART = ARB_DIR / "library_strings.dart"
PREFIX = "libItem_"


def key_of(item_id: str) -> str:
    return PREFIX + re.sub(r"[^A-Za-z0-9]", "_", item_id)


def items() -> list[dict]:
    lib = tomllib.loads(TOML.read_text(encoding="utf-8"))
    out = []
    for t in lib.get("template", []):
        out.append({"id": t["id"], "name": t["display_name"], "description": t.get("description", ""), "keywords": t.get("keywords", [])})
    for s in lib.get("source", []):
        out.append({"id": s["id"], "name": s["display_name"], "description": s.get("description", ""), "keywords": s.get("keywords", [])})
    return out


def strings_for(locale: str, all_items: list[dict], l10n: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for it in all_items:
        k = key_of(it["id"])
        if locale == "en":
            out[f"{k}_name"] = it["name"]
            out[f"{k}_description"] = it["description"]
            out[f"{k}_tags"] = " ".join(it["keywords"])
        else:
            entry = l10n["items"].get(it["id"], {}).get(locale)
            if entry is None:
                raise SystemExit(f"{L10N}: {it['id']} has no {locale} entry")
            out[f"{k}_name"] = entry["name"]
            out[f"{k}_description"] = entry["description"]
            out[f"{k}_tags"] = entry["tags"]
    return out


def write_arb(name: str, locale: str, strings: dict[str, str]) -> str:
    path = ARB_DIR / name
    data = json.loads(path.read_text(encoding="utf-8"))
    # drop stale library keys, keep everything else in place
    for k in list(data):
        if k.startswith(PREFIX) or k.startswith("@" + PREFIX):
            del data[k]
    for k, v in strings.items():
        data[k] = v
        if locale == "en":
            data["@" + k] = {"description": "Standard Library item (library/std/concepts.toml); generated by scripts/gen_library_l10n.py."}
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def dart(all_items: list[dict]) -> str:
    lines = [
        "// GENERATED by scripts/gen_library_l10n.py from library/std/concepts.toml",
        "// and locale/library/std.json — do not edit by hand.",
        "",
        "/// The localized presentation of a Standard Library item, by id:",
        "/// its name, description and search tags in the current locale",
        "/// (docs/project/localization-style.md).  Falls back to the item's",
        "/// canonical English (what the daemon sends) for an id the catalog",
        "/// does not know — a future team or project library.",
        "library;",
        "",
        "import 'app_localizations.dart';",
        "",
        "class LibraryItemStrings {",
        "  const LibraryItemStrings({required this.name, required this.description, required this.tags});",
        "  final String name;",
        "  final String description;",
        "",
        "  /// Space-separated words a search should match, in the locale.",
        "  final String tags;",
        "}",
        "",
        "LibraryItemStrings? libraryItemStrings(AppLocalizations l10n, String id) => switch (id) {",
    ]
    for it in all_items:
        k = key_of(it["id"])
        # laid out as `dart format --page-width 100` leaves it
        lines += [
            f"  '{it['id']}' => LibraryItemStrings(",
            f"    name: l10n.{k}_name,",
            f"    description: l10n.{k}_description,",
            f"    tags: l10n.{k}_tags,",
            "  ),",
        ]
    lines += ["  _ => null,", "};", ""]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    all_items = items()
    l10n = json.loads(L10N.read_text(encoding="utf-8"))
    outputs: dict[Path, str] = {}
    for locale, name in ARBS.items():
        outputs[ARB_DIR / name] = write_arb(name, locale, strings_for(locale, all_items, l10n))
    outputs[DART] = dart(all_items)
    changed = [p for p, text in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    if check:
        for p in changed:
            print(f"stale: {p.relative_to(ROOT)}")
        return 1 if changed else 0
    for p, text in outputs.items():
        p.write_text(text, encoding="utf-8")
    print(f"{len(all_items)} items, {len(changed)} file(s) written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
