//! Generated by bdl-codegen-rust 0.1.0 for design `concepts_ordered`. Do not edit.
//!
//! One global tick = `step`: read phase (every due declaration, in plan order,
//! reading inputs, declarations evaluated earlier this tick, and *committed* state),
//! write phase (every cell whose writing domain is active, into the next state),
//! commit, then output projection.  Nothing is mutated in place; reads never see
//! writes of the same tick.  Semantics: docs/spec/runtime-semantics.md.

#![no_std]
#![forbid(unsafe_code)]
#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, clippy::all)]

use bdl_runtime_core::num;
use bdl_runtime_core::prim;
use bdl_runtime_core::read_decl;
use bdl_runtime_core::read_decl_ref;
use bdl_runtime_core::read_input;
use bdl_runtime_core::ActiveDomains;
use bdl_runtime_core::ClockSlot;
use bdl_runtime_core::RuntimeError;

/// The design this core was generated from.
pub const DESIGN: &str = "concepts_ordered";

/// Whether the design has any clock domain; decides when domain-agnostic declarations run (DI-16).
pub const HAS_DOMAINS: bool = true;

pub const CLOCK_COUNT: u16 = 1_u16;

/// Clock domain `main` (clk#0).
pub const CLOCK_0: ClockSlot = ClockSlot(0_u16);

/// Concept `Brightness` (sem#0): q[1].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sem0(pub f64);

/// Concept `Opacity` (sem#1): q[1].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sem1(pub f64);

/// Concept `Mode` (sem#2): nat.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sem2(pub u64);

/// Temporal state: one slot per `delay`/`sync` site, `None` until first written.
/// Slot ↔ `StateCellId` in `bdl-manifest.json`.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Cells {}

/// Everything that survives from one tick to the next.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct State {
    pub cells: Cells,
}

/// Values for the unresolved declarations at one tick.
/// A `None` for a declaration that is due is `RuntimeError::MissingInput`, never a default.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Inputs {
    pub decl_0: Option<Sem0>,
    pub decl_1: Option<Sem0>,
    pub decl_2: Option<Sem1>,
    pub decl_3: Option<Sem2>,
    pub decl_4: Option<Sem2>,
}

/// Every declaration's value at one tick; `None` when it was not due.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Values {
    pub decl_0: Option<Sem0>,
    pub decl_1: Option<Sem0>,
    pub decl_2: Option<Sem1>,
    pub decl_3: Option<Sem2>,
    pub decl_4: Option<Sem2>,
    pub decl_5: Option<Sem0>,
    pub decl_6: Option<Sem0>,
    pub decl_7: Option<bool>,
    pub decl_8: Option<bool>,
    pub decl_9: Option<bool>,
    pub decl_10: Option<Sem1>,
    pub decl_11: Option<bool>,
}

/// Physical outputs committed at one tick: the single driver's value, `None` when the driver was not due.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Outputs {}

/// Raw commands of the realised outputs at one tick: each device binding's encoder applied to its output's value, `None` when the driver was not due.
/// Downstream of `Values` and `Outputs`, which never depend on it (docs/architecture/output-realization.md).
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Commands {}

/// The observable result of one tick.
#[derive(Clone, Copy, Debug, PartialEq, Default)]
pub struct Tick {
    pub values: Values,
    pub outputs: Outputs,
    pub commands: Commands,
}

/// The initial state: no cell has been written.
pub fn init() -> State {
    State::default()
}

/// One global tick with the given active domains and inputs.
/// On `Err` the state is unchanged.
pub fn step(state: &mut State, active: ActiveDomains, inputs: &Inputs) -> Result<Tick, RuntimeError> {
    let prev: &Cells = &state.cells;
    // read phase
    // b1 (decl#0)
    let decl_0: Option<Sem0> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_0, 0_u64)?) } else { None };
    // b2 (decl#1)
    let decl_1: Option<Sem0> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_1, 1_u64)?) } else { None };
    // o (decl#2)
    let decl_2: Option<Sem1> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_2, 2_u64)?) } else { None };
    // m1 (decl#3)
    let decl_3: Option<Sem2> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_3, 3_u64)?) } else { None };
    // m2 (decl#4)
    let decl_4: Option<Sem2> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_4, 4_u64)?) } else { None };
    // dimmer (decl#5)
    let decl_5: Option<Sem0> = if active.is_active(CLOCK_0) { Some({ let l0 = read_decl(&decl_0, 0_u64)?; { let l1 = read_decl(&decl_1, 1_u64)?; if (&l0.clone().0 < &l1.clone().0) { l0.clone() } else { l1.clone() } } }) } else { None };
    // clipped (decl#6)
    let decl_6: Option<Sem0> = if active.is_active(CLOCK_0) { Some({ let l2 = read_decl(&decl_0, 0_u64)?; { let l3 = Sem0(0.2_f64); { let l4 = Sem0(0.8_f64); { let l7 = l3; { let l8 = { let l5 = l2; { let l6 = l4; if (&l5.clone().0 < &l6.clone().0) { l5.clone() } else { l6.clone() } } }; if (&l7.clone().0 < &l8.clone().0) { l8.clone() } else { l7.clone() } } } } } }) } else { None };
    // sameB (decl#7)
    let decl_7: Option<bool> = if active.is_active(CLOCK_0) { Some((read_decl_ref(&decl_0, 0_u64)? == read_decl_ref(&decl_1, 1_u64)?)) } else { None };
    // sameMode (decl#8)
    let decl_8: Option<bool> = if active.is_active(CLOCK_0) { Some((read_decl_ref(&decl_3, 3_u64)? == read_decl_ref(&decl_4, 4_u64)?)) } else { None };
    // below (decl#9)
    let decl_9: Option<bool> = if active.is_active(CLOCK_0) { Some((&read_decl(&decl_0, 0_u64)?.0 < &read_decl(&decl_1, 1_u64)?.0)) } else { None };
    // asOpacity (decl#10)
    let decl_10: Option<Sem1> = if active.is_active(CLOCK_0) { Some(Sem1(read_decl(&decl_0, 0_u64)?.0)) } else { None };
    // sameAsO (decl#11)
    let decl_11: Option<bool> = if active.is_active(CLOCK_0) { Some((read_decl_ref(&decl_10, 10_u64)? == read_decl_ref(&decl_2, 2_u64)?)) } else { None };
    // write phase: every active writer's operand, before any commit
    // commit: only the cells written this tick change; nothing else is copied
    // machine sinks: each realised output's raw command, when its driver was due
    Ok(Tick { values: Values { decl_0: decl_0, decl_1: decl_1, decl_2: decl_2, decl_3: decl_3, decl_4: decl_4, decl_5: decl_5, decl_6: decl_6, decl_7: decl_7, decl_8: decl_8, decl_9: decl_9, decl_10: decl_10, decl_11: decl_11 }, outputs: Outputs {}, commands: Commands {} })
}
