//! Rust code generation for a lowered design.
//!
//! ```text
//! ExecIr ──emit──▶ ast::Module ──print──▶ src/lib.rs      (no_std semantic core)
//!        ──host──▶ ast::Module ──print──▶ src/bin/host.rs (std bridge, feature "host")
//!        ──manifest──▶ bdl-manifest.json
//!        ──────────▶ Cargo.toml
//! ```
//!
//! Deterministic: the same `ExecIr` yields byte-identical files.  Nothing
//! here rediscovers dependencies, state cells, clocks or writer domains —
//! they arrive explicit in the plan.  The core is target-independent: no
//! HAL, no pin, no peripheral type; the platform adapter is a later,
//! separate artefact.

#![forbid(unsafe_code)]

pub mod ast;
pub mod emit;
pub mod host;
pub mod manifest;
pub mod names;
pub mod print;

use bdl_exec_ir::ExecIr;
use std::collections::BTreeMap;

pub use emit::EmitError;
pub use manifest::{Manifest, MANIFEST_VERSION};

/// The generator's identity, written into every artefact.
pub fn generator() -> String {
    format!("bdl-codegen-rust {}", env!("CARGO_PKG_VERSION"))
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CodegenOptions {
    /// Path to `bdl-runtime-core`, as written into the generated
    /// `Cargo.toml` (relative to the generated crate, or absolute).
    pub runtime_core_path: String,
    /// Path to `bdl-runtime-host`.
    pub runtime_host_path: String,
}

impl Default for CodegenOptions {
    fn default() -> Self {
        CodegenOptions {
            runtime_core_path: "../../runtime/bdl-runtime-core".into(),
            runtime_host_path: "../../runtime/bdl-runtime-host".into(),
        }
    }
}

/// A generated crate: relative path → contents.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedCrate {
    pub package: String,
    pub files: BTreeMap<String, String>,
    pub manifest: Manifest,
}

impl GeneratedCrate {
    pub fn core_source(&self) -> &str {
        self.files
            .get("src/lib.rs")
            .map(String::as_str)
            .unwrap_or("")
    }
    /// Lines of generated core source (a baseline metric).
    pub fn core_lines(&self) -> usize {
        self.core_source().lines().count()
    }
    pub fn total_bytes(&self) -> usize {
        self.files.values().map(String::len).sum()
    }
}

pub fn generate(ir: &ExecIr, options: &CodegenOptions) -> Result<GeneratedCrate, EmitError> {
    let package = names::package(&ir.name);
    let generator = generator();
    let core = emit::core_module(ir, &generator)?;
    let host = host::host_module(ir, &package, &generator)?;
    let manifest = manifest::manifest(ir, &package, &generator);
    let manifest_json =
        serde_json::to_string_pretty(&manifest).map_err(|e| EmitError(e.to_string()))?;
    let mut files = BTreeMap::new();
    files.insert("Cargo.toml".to_string(), cargo_toml(&package, options));
    files.insert("src/lib.rs".to_string(), print::module(&core));
    files.insert("src/bin/host.rs".to_string(), print::module(&host));
    files.insert("bdl-manifest.json".to_string(), manifest_json + "\n");
    Ok(GeneratedCrate {
        package,
        files,
        manifest,
    })
}

fn cargo_toml(package: &str, o: &CodegenOptions) -> String {
    format!(
        "# Generated by {gen}. Do not edit.\n\
         [package]\n\
         name = \"{package}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         \n\
         # A generated crate is its own workspace, wherever it is written.\n\
         [workspace]\n\
         \n\
         [lib]\n\
         path = \"src/lib.rs\"\n\
         \n\
         [[bin]]\n\
         name = \"host\"\n\
         path = \"src/bin/host.rs\"\n\
         required-features = [\"host\"]\n\
         \n\
         [features]\n\
         default = []\n\
         # The std host bridge; the core itself is no_std.\n\
         host = [\"dep:bdl-runtime-host\"]\n\
         \n\
         [dependencies]\n\
         bdl-runtime-core = {{ path = {core:?} }}\n\
         bdl-runtime-host = {{ path = {host:?}, optional = true }}\n",
        gen = generator(),
        core = o.runtime_core_path,
        host = o.runtime_host_path,
    )
}
