//! Generated by bdl-codegen-rust 0.1.0 for design `collections`. Do not edit.
//!
//! One global tick = `step`: read phase (every due declaration, in plan order,
//! reading inputs, declarations evaluated earlier this tick, and *committed* state),
//! write phase (every cell whose writing domain is active, into the next state),
//! commit, then output projection.  Nothing is mutated in place; reads never see
//! writes of the same tick.  Semantics: docs/spec/runtime-semantics.md.

#![no_std]
#![forbid(unsafe_code)]
#![allow(unused_imports, unused_variables, unused_mut, unused_parens, dead_code, clippy::all)]

extern crate alloc;
use alloc::vec::Vec;
use bdl_runtime_core::list;
use bdl_runtime_core::num;
use bdl_runtime_core::prim;
use bdl_runtime_core::read_decl;
use bdl_runtime_core::read_input;
use bdl_runtime_core::ActiveDomains;
use bdl_runtime_core::ClockSlot;
use bdl_runtime_core::RuntimeError;

/// The design this core was generated from.
pub const DESIGN: &str = "collections";

/// Whether the design has any clock domain; decides when domain-agnostic declarations run (DI-16).
pub const HAS_DOMAINS: bool = true;

pub const CLOCK_COUNT: u16 = 1_u16;

/// Clock domain `main` (clk#0).
pub const CLOCK_0: ClockSlot = ClockSlot(0_u16);

/// Temporal state: one slot per `delay`/`sync` site, `None` until first written.
/// Slot ↔ `StateCellId` in `bdl-manifest.json`.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Cells {
    pub cell_0: Option<Vec<f64>>,
}

/// Everything that survives from one tick to the next.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct State {
    pub cells: Cells,
}

/// Values for the unresolved declarations at one tick.
/// A `None` for a declaration that is due is `RuntimeError::MissingInput`, never a default.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Inputs {
    pub decl_0: Option<Vec<f64>>,
}

/// Every declaration's value at one tick; `None` when it was not due.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Values {
    pub decl_0: Option<Vec<f64>>,
    pub decl_1: Option<bool>,
    pub decl_2: Option<f64>,
    pub decl_3: Option<Vec<f64>>,
    pub decl_4: Option<(f64, f64)>,
    pub decl_5: Option<f64>,
    pub decl_6: Option<bool>,
    pub decl_7: Option<Vec<f64>>,
    pub decl_8: Option<Vec<(f64, f64)>>,
    pub decl_9: Option<bool>,
    pub decl_10: Option<f64>,
    pub decl_11: Option<Vec<f64>>,
}

/// Physical outputs committed at one tick: the single driver's value, `None` when the driver was not due.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Outputs {}

/// The observable result of one tick.
#[derive(Clone, Debug, PartialEq, Default)]
pub struct Tick {
    pub values: Values,
    pub outputs: Outputs,
}

/// The initial state: no cell has been written.
pub fn init() -> State {
    State::default()
}

/// One global tick with the given active domains and inputs.
/// On `Err` the state is unchanged.
pub fn step(state: &mut State, active: ActiveDomains, inputs: &Inputs) -> Result<Tick, RuntimeError> {
    let prev: &Cells = &state.cells;
    let mut next: Cells = state.cells.clone();
    // read phase
    // xs (decl#0)
    let decl_0: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some(read_input(&inputs.decl_0, 0_u64)?) } else { None };
    // above (decl#1)
    let decl_1: Option<bool> = if active.is_active(CLOCK_0) { Some({ let l0 = read_decl(&decl_0, 0_u64)?; list::fold(l0, false, |l1, l2| Ok({ let l3 = l1.clone(); { let l4 = l2.clone(); prim::or({ let l5 = l3.clone(); (2.0_f64 < l5.clone()) }, l4.clone()) } }))? }) } else { None };
    // total (decl#2)
    let decl_2: Option<f64> = if active.is_active(CLOCK_0) { Some({ let l6 = read_decl(&decl_0, 0_u64)?; list::fold(l6, 0.0_f64, |l7, l8| Ok(num::add(l7.clone(), l8.clone(), 2_u64)?))? }) } else { None };
    // shifted (decl#3)
    let decl_3: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some({ let l9 = read_decl(&decl_0, 0_u64)?; list::fold(l9, list::nil::<f64>(), |l10, l11| Ok({ let l12 = l10.clone(); { let l13 = l11.clone(); list::cons({ let l14 = l12.clone(); num::add(l14.clone(), 5.0_f64, 3_u64)? }, l13.clone()) } }))? }) } else { None };
    // stats (decl#4)
    let decl_4: Option<(f64, f64)> = if active.is_active(CLOCK_0) { Some((prim::get_d(list::head(read_decl(&decl_0, 0_u64)?), 0.0_f64), list::length(read_decl(&decl_0, 0_u64)?))) } else { None };
    // first (decl#5)
    let decl_5: Option<f64> = if active.is_active(CLOCK_0) { Some(read_decl(&decl_4, 4_u64)?.0) } else { None };
    // same (decl#6)
    let decl_6: Option<bool> = if active.is_active(CLOCK_0) { Some((read_decl(&decl_0, 0_u64)? == list::reverse(list::reverse(read_decl(&decl_0, 0_u64)?)))) } else { None };
    // remembered (decl#7)
    let decl_7: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some(match &prev.cell_0 { Some(v) => v.clone(), None => list::nil::<f64>() }) } else { None };
    // pairs (decl#8)
    let decl_8: Option<Vec<(f64, f64)>> = if active.is_active(CLOCK_0) { Some({ let l15 = read_decl(&decl_0, 0_u64)?; { let l16 = read_decl(&decl_3, 3_u64)?; list::reverse(list::fold(list::reverse(l15), (l16, list::nil::<(f64, f64)>()), |l17, l18| Ok({ let l19 = l17.clone(); { let l20 = l18.clone(); (list::drop(1.0_f64, l20.clone().0), list::fold(list::fold(list::take(1.0_f64, l20.clone().0), list::nil::<(f64, f64)>(), |l21, l22| Ok({ let l23 = l21.clone(); { let l24 = l22.clone(); list::cons((l19.clone(), l23.clone()), l24.clone()) } }))?, l20.clone().1, |l25, l26| Ok(list::cons(l25.clone(), l26.clone())))?) } }))?.1) } }) } else { None };
    // has2 (decl#9)
    let decl_9: Option<bool> = if active.is_active(CLOCK_0) { Some({ let l27 = 2.0_f64; { let l28 = read_decl(&decl_0, 0_u64)?; list::fold(l28, false, |l29, l30| Ok({ let l31 = l29.clone(); { let l32 = l30.clone(); prim::or((l27.clone() == l31.clone()), l32.clone()) } }))? } }) } else { None };
    // clipped (decl#10)
    let decl_10: Option<f64> = if active.is_active(CLOCK_0) { Some({ let l33 = read_decl(&decl_2, 2_u64)?; { let l34 = 1.0_f64; { let l35 = 4.0_f64; { let l38 = l34; { let l39 = { let l36 = l33; { let l37 = l35; prim::ite((l36 < l37), l36, l37) } }; prim::ite((l38 < l39), l39, l38) } } } } }) } else { None };
    // kept (decl#11)
    let decl_11: Option<Vec<f64>> = if active.is_active(CLOCK_0) { Some({ let l40 = read_decl(&decl_0, 0_u64)?; list::fold(l40, list::nil::<f64>(), |l41, l42| Ok({ let l43 = l41.clone(); { let l44 = l42.clone(); prim::ite({ let l45 = l43.clone(); (l45.clone() < 2.0_f64) }, list::cons(l43.clone(), l44.clone()), l44.clone()) } }))? }) } else { None };
    // write phase: into the next state only
    // cell_0 at [] in remembered (decl#7)
    if active.is_active(CLOCK_0) { next.cell_0 = Some(read_decl(&decl_0, 0_u64)?); }
    // commit
    state.cells = next;
    Ok(Tick { values: Values { decl_0: decl_0, decl_1: decl_1, decl_2: decl_2, decl_3: decl_3, decl_4: decl_4, decl_5: decl_5, decl_6: decl_6, decl_7: decl_7, decl_8: decl_8, decl_9: decl_9, decl_10: decl_10, decl_11: decl_11 }, outputs: Outputs {} })
}
